version: "3.8"
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5174:5174"
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge